### ISSUE TITLE
Error dling a channel

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#202] opened 2022-08-30 15:52 UTC
Just had this pop up for a new channel

[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 106, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 46, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription.py", line 361, in download
    for entry in downloader.download():
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/youtube/channel.py", line 165, in download
    as_single_video_dict = self.extract_info_with_retry(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 165, in extract_info_with_retry
    entry_dict = self.extract_info(ytdl_options_overrides=ytdl_options_overrides, **kwargs)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 131, in extract_info
    with self.ytdl_downloader(ytdl_options_overrides) as ytdl_downloader:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 103, in ytdl_downloader
    ytdl_options = self._ytdl_options_builder.clone().add(ytdl_options_overrides).to_dict()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/ytdl_options_builder.py", line 42, in add
    mergedeep.merge(self._ytdl_options, *non_empty, strategy=strategy)
  File "/usr/lib/python3.10/site-packages/mergedeep/mergedeep.py", line 100, in merge
    return reduce(partial(_deepmerge, strategy=strategy), sources, destination)
  File "/usr/lib/python3.10/site-packages/mergedeep/mergedeep.py", line 84, in _deepmerge
    _handle_merge.get(strategy)(dst, src, key)
  File "/usr/lib/python3.10/site-packages/mergedeep/mergedeep.py", line 52, in _handle_merge_typesafe
    raise TypeError(
TypeError: destination type: <class 'str'> differs from source type: <class 'NoneType'> for key: "download_archive"
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.1zpgmadq' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!

[config.zip](https://github.com/jmbannon/ytdl-sub/files/9454419/config.zip)

**Comment by jmbannon** [comment] 2022-08-30 17:14
Duplicate of https://github.com/jmbannon/ytdl-sub/issues/190

**Closed by jmbannon** 2022-08-30 17:14 UTC
