### ISSUE TITLE
Log file: ERROR: Conversion failed! [Metadata] There isn't any metadata to add

### ISSUE THREAD

**Issue by talkingseedling** [jmbannon/ytdl-sub#373] opened 2022-11-28 03:59 UTC
ytdl-sub used: v0.5
Error:
[ytdl-sub:yt-dlp] [Merger] Merging formats into "/tmp/ytdl-sub-downloads/dreamingspanish_B/2jSBTh3xefc.webm"
[ytdl-sub:yt-dlp] ERROR: Conversion failed!
[ytdl-sub:yt-dlp] [Metadata] There isn't any metadata to add
[ytdl-sub:downloader] Failed to download entry.

download of https://www.youtube.com/playlist?list=PLlpPf-YgbU7HWrrenMs3-nuhxgzyAiA-C
fails at https://www.youtube.com/watch?v=2jSBTh3xefc&list=PLlpPf-YgbU7HWrrenMs3-nuhxgzyAiA-C&index=90

error log: https://pastebin.com/XXpWbV4s
config: https://pastebin.com/8Hssv62V
subscription: https://pastebin.com/sLeDNNsp

**Comment by jmbannon** [comment] 2022-11-28 07:13
Thank for the details. I am able to reproduce. It seems like yt-dlp is trying to merge two .webm files but fails. Then ytdl-sub can't fine the expected merged output video

**Comment by jmbannon** [comment] 2022-11-28 07:26
Looks like it's hitting this issue: https://github.com/ytdl-org/youtube-dl/issues/28042

**Comment by jmbannon** [comment] 2022-11-28 07:30
Adding 
```
ytdl_options:
  format: "bestvideo[ext=mp4]+bestaudio[ext=m4a]"
```
solves the issue for me. Going to close this out - please reopen if it's still an issue.

**Closed by jmbannon** 2022-11-28 07:30 UTC
Labels: bug
