### ISSUE TITLE
When using video title regex filters, place check before downloading metadata 

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#313] opened 2022-11-08 23:36 UTC
This would save on bandwidth and make it possible to efficiently download select videos from a large set of videos

**Comment by jmbannon** [comment] 2022-11-09 01:33
closing, duplicate of https://github.com/jmbannon/ytdl-sub/issues/219

**Closed by jmbannon** 2022-11-09 01:33 UTC
