### ISSUE TITLE
Getting permission error when running config/run-cron

### ISSUE THREAD

**Issue by smshapiro85** [jmbannon/ytdl-sub#803] opened 2023-11-05 18:04 UTC
Hello! I fully realize this is an issue with my limited knowledge of docker, but I am hoping to get some help with the cron setup as I am not able to get the test command working when logged in as "abc" user.

Here is my docker-compose file that I have running in portainer, running on a synology NAS:

```
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub-gui:latest
    container_name: ytdl-sub
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - /volume1/docker/ytdl-sub:/config
      - /volume1/Music/ytdl-sub:/music  # optional
    ports:
      - 9010:8443
    restart: unless-stopped
```

After following the instructions listed on the knowledge base here: https://github.com/jmbannon/ytdl-sub/wiki/7.-Automate-Downloading-New-Content-Using-Your-Configs

I log back into the container console as user "abc" but get this permissions error:

<img width="1289" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/41717535/76e2b31e-3c53-47a5-9bc3-ce281b967c2e">

I also confirmed the IDs of the abc user:

<img width="502" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/41717535/ee170944-f00a-4e22-a123-5fed835c046a">

Running the `/config/run_cron` command as root worked successfully.

Any help would be greatly appreciated!

**Comment by jmbannon** [comment] 2023-11-05 19:47
login as root and give abc permission to /config, it looks like it doesn't have permissions to create the working directory `/config/.ytdl-sub-working-directory/`

**Comment by jmbannon** [comment] 2023-11-05 20:08
Still happy to help - but gonna close both issues since they're more-so support questions

**Comment by smshapiro85** [comment] 2023-11-05 21:59
Thank you Jesse! I tried `chmod 777 /config` as root in the container terminal, but I am still getting the permission error when running the `/config/run_cron` command, do you have any recommendations? Really appreciate your help.

**Comment by jmbannon** [comment] 2023-11-05 22:22
`chown abc:abc /config`

**Comment by smshapiro85** [comment] 2023-11-06 15:42
I think there is something else going on with my permissions and docker... when I list the files in the /config folder in terminal, it only sees a subset of them:

![image](https://github.com/jmbannon/ytdl-sub/assets/41717535/dfacd26b-5ffc-4420-891d-dade00d76921)

Whereas this is what the directory looks like in synology:

![image](https://github.com/jmbannon/ytdl-sub/assets/41717535/317e5665-cad2-421e-9bcd-6b50b82b07be)

**Comment by bullwinkl** [comment] 2023-11-07 15:38
I hate to re-open a closed issue, but I'm having the same problem...but I think I have a clue as to what's happening.  I can execute "run_cron" fine when I'm in the /config directory which abc is the owner of.  If I try and run it from outside directory with "./config/run_cron" I get the same error...specifically `PermissionError: [Errno 13] Permission denied: '.ytdl-sub-downloads'`.

I have run it from another directory, where abc had all the perms needed, and it created the .ytdl-sub-downloads file _in that directory_.  I don't think that's the desired behavior is it?

Just to confirm, here are the steps I took to recreate the situation:

1. logged in as `root` and created directory `/test_dir`
2. chowned` /test_dir` for `abc:abc` and confirmed
3. logged in as `abc` and entered `/test_dir`
4. ran `.././config/run_cron`
5. `ls -al` showed a new directory `.ytdl-sub-downloads` had been created inside `/test_dir`

**Comment by jmbannon** [comment] 2023-11-07 15:53
I think abc needs write permission in /config
As root can you try `chown abc:abc /config`, then test if abc can create a dir in there

**Comment by bullwinkl** [comment] 2023-11-07 16:05
Sorry, I should have mentioned I'd done that first, and that works, but only if you're executing the run_cron script while inside /config. When the the cron job is run, though,  I think it's trying  to run in the root dir and it doesn't have write perms in there to create the`.ytdl-sub-downloads` dir in there.  I'm going to test that theory by manually creating `/.ytdl-sub-downloads`, giving it to abc:abc and seeing if the cron job runs properly then--in a work meeting right now though, so will probably be an hour or so before I can get back to it.

**Comment by smshapiro85** [comment] 2023-11-07 16:11
I am having the same issue as bullwinkl- if I cd into the /config directory, the run_cron command works, but if i am in the root directory i get the permissions error.

**Comment by bullwinkl** [comment] 2023-11-07 17:54
welp, the working directory isn't the root directory.  No dice on the cron job.

**Comment by jmbannon** [comment] 2023-11-07 17:56
Hang tight, just updated the wiki (forgot to update it for the GUI image - sorry!). Testing now

**Comment by jmbannon** [comment] 2023-11-07 18:19
Okay I confirmed the new instructions work on the GUI image, but it seems LSIO doesn't show the cron stdout by default in the docker logs. Will try to fix that later today

**Comment by jmbannon** [comment] 2023-11-17 07:51
Going to close this out assuming it's fixed. Please feel free to reopen if there are any issue

**Closed by jmbannon** 2023-11-17 07:51 UTC

**Comment by BadCo-NZ** [comment] 2023-11-25 09:15
I am still getting permission denied when following the latest docs with the headless container.

```
abc@dd4527ff24c7:/$ /config/run_cron
bash: /config/run_cron: Permission denied

abc@dd4527ff24c7:/config$ ./run_cron
bash: ./run_cron: Permission denied
```

**Comment by jmbannon** [comment] 2023-11-25 17:34
@BadCo-NZ My guess is you logged in a root to make the files. Log back in as root and do `chown abc:abc ./run_,cron` and on the crontab abc file

**Comment by BadCo-NZ** [comment] 2023-11-25 20:19
> @BadCo-NZ My guess is you logged in a root to make the files. Log back in as root and do `chown abc:abc ./run_cron` and on the crontab abc file. Also make sure your run_cron script cds into the /config directory so abc does not run in the root folder

Thanks for the reply and sorry I should have mentioned I tried everything in this thread already.

```
drwxr-xr-x   6 abc  users  4096 May 25  2023 config
```

```
abc@dd4527ff24c7:/$ ls -la /config/
total 56
drwxr-xr-x 6 abc  users 4096 May 25  2023 .
drwxr-xr-x 1 root root  4096 Nov 25 22:06 ..
-rw------- 1 abc  users 1770 Nov 26 09:15 .bash_history
drwxr-xr-x 3 abc  users 4096 May 13  2023 .cache
drwxr-xr-x 2 abc  users 4096 May 28 15:34 .ytdl-sub-downloads
-rw-r--r-- 1 abc  users 4931 May 25  2023 config.yaml
-rw-r--r-- 1 abc  users 4774 May 25  2023 config.yaml.old
drwxr-xr-x 2 abc  users 4096 May 13  2023 crontabs
drwxr-xr-x 2 abc  users 4096 May 13  2023 examples
-rwxr-xr-x 1 abc  users  120 Nov 25 22:02 run_cron
-rw-r--r-- 1 abc  users 6262 May 13  2023 subscriptions.yaml
```

**Comment by jmbannon** [comment] 2023-11-25 21:06
To sanity check, can you post your `run_cron` script @BadCo-NZ ?

**Comment by BadCo-NZ** [comment] 2023-11-25 21:38
> To sanity check, can you post your `run_cron` script @BadCo-NZ ?

Sure mate

```
abc@dd4527ff24c7:/$ cat /config/run_cron 
#!/bin/bash

echo 'Cron started, running ytdl-sub...'

cd /config

ytdl-sub --config=config.yaml sub subscriptions.yaml
```

**Comment by jmbannon** [comment] 2023-11-26 00:14
Hmmmm. Can you pinpoint which command gives the permission error? Is it `ytdl-sub` ?

**Comment by BadCo-NZ** [comment] 2023-11-27 09:41
> Hmmmm. Can you pinpoint which command gives the permission error? Is it `ytdl-sub` ?

`cd` and `ytdl-sub` work fine when run in terminal.

I did find the below methods work fine when running the sript:

```
bash run_cron
sh run_cron
source run_cron
. run_cron
```

I have amended the crontab with one of the above options, I'll check back tomorrow to see if it runs fine.
