### ISSUE TITLE
File ownership

### ISSUE THREAD

**Issue by glottisfaun0000** [jmbannon/ytdl-sub#1020] opened 2024-07-10 00:37 UTC
Files created don't follow the PID/GID/UMASK of my compose and instead have these permissions: `drwxr-xr-x 3 0 0 4096` (root) which means Jellyfin can't delete them from the UI. Is this intended behavior? What's the point of created files not following the env variables?

**Comment by jmbannon** [comment] 2024-07-10 00:59
Most likely you ran ytdl-sub as root

**Comment by glottisfaun0000** [comment] 2024-07-10 03:11
Totally correct, I thought a docker exec would inherit the PUID/PGID from environmental variables on a running container. Adding `-u 1000:1000` to my exec fixed it.

With the subscription run working now, the files in Jellyfin are basically unusable because the `Season / episode - season.episode` string leading the title is so long that the video title information is basically lost. Like for [this video](https://www.youtube.com/watch?v=sFE-9un1PXM) downloaded through a subscription, all Jellyfin will show me except as a banner once the video is playing is:  `Season 2024 - 62901. s2024.e062901 - Game Boy vs. Super Game Boy...`

**Comment by jmbannon** [comment] 2024-07-10 05:47
Jellyfin metadata is read through NFOs, not filename. Make sure your JF library prioritizes local metadata and it should scrape as intended

**Comment by glottisfaun0000** [comment] 2024-07-10 05:50
>[It's currently not possible to disable .nfo metadata. Local metadata will always be fetched and has priority over remote metadata providers like TMDb.](https://jellyfin.org/docs/general/server/metadata/nfo/)

**Comment by jmbannon** [comment] 2024-07-10 14:59
Can you upload your config, subscriptions, and a screenshot of your JF library settings

**Comment by jmbannon** [comment] 2024-09-20 15:23
Closing but still happy to help if there's still an issue

**Closed by jmbannon** 2024-09-20 15:23 UTC
